// const ACTION={
//     USER_LOGGED_IN:"USER_LOGGED_IN",
//     CLOUDINARY_IMAGE:"CLOUDINARY_IMAGE",
//     SEARCH_POST:"SEARCH_POST",
//     CHALLENGE_POST:"CHALLENGE_POST",
//     COMMUNITY_POST:"COMMUNITY_POST",
//     COMMUNITY:"COMMUNITY"
// }

// export default ACTION

export const IS_USER_LOGGED_IN = 'IS_USER_LOGGED_IN';
export const LOGGED_IN_USER_DETAIL = 'LOGGED_IN_USER_DETAIL';
